stages:
  - deploy

image: registry.gitlab.com/redmic-project/docker/docker-deploy

services:
  - docker:dind

variables:
  GIT_SUBMODULE_STRATEGY: normal
  DOCKER_DRIVER: overlay2
  DEPLOY_DIR_NAME: '.'
  STATUS_CHECK_DELAY: 60
  STACK: metric
  SERVICES_TO_CHECK: metric_dockerd-exporter metric_cadvisor metric_grafana metric_alertmanager metric_unsee metric_node-exporter metric_prometheus

deploy-dev:
  stage: deploy
  variables:
    SSH_REMOTE: ${DEV_SSH_REMOTE}
    ADMIN_USER: ${DEV_ADMIN_USER}
    ADMIN_PASSWORD: ${DEV_ADMIN_PASSWORD}
    DOCKER_GWBRIDGE_IP: ${DEV_DOCKER_GWBRIDGE_IP}
    UI_AUTH: ${DEV_UI_AUTH}
    PUBLIC_HOSTNAME: ${DEV_PUBLIC_HOSTNAME}
  script:
    - create-nets.sh metric-net
    - >
      deploy.sh ADMIN_USER=${ADMIN_USER} ADMIN_PASSWORD=${ADMIN_PASSWORD} DOCKER_GWBRIDGE_IP=${DOCKER_GWBRIDGE_IP}
      UI_AUTH=${UI_AUTH} PUBLIC_HOSTNAME=${PUBLIC_HOSTNAME}
  environment:
    name: dev
  only:
    - dev
  when: manual

deploy-supporting-branch:
  stage: deploy
  variables:
    SSH_REMOTE: ${DEV_SSH_REMOTE}
    ADMIN_USER: ${DEV_ADMIN_USER}
    ADMIN_PASSWORD: ${DEV_ADMIN_PASSWORD}
    DOCKER_GWBRIDGE_IP: ${DEV_DOCKER_GWBRIDGE_IP}
    UI_AUTH: ${DEV_UI_AUTH}
    PUBLIC_HOSTNAME: ${DEV_PUBLIC_HOSTNAME}
  script:
    - create-nets.sh metric-net
    - >
      deploy.sh ADMIN_USER=${ADMIN_USER} ADMIN_PASSWORD=${ADMIN_PASSWORD} DOCKER_GWBRIDGE_IP=${DOCKER_GWBRIDGE_IP}
      UI_AUTH=${UI_AUTH} PUBLIC_HOSTNAME=${PUBLIC_HOSTNAME}
  environment:
    name: dev
  only:
    - branches
  except:
    - master
    - dev
  when: manual

deploy-pro:
  stage: deploy
  variables:
    SSH_REMOTE: ${PRO_SSH_REMOTE}
    ADMIN_USER: ${PRO_ADMIN_USER}
    ADMIN_PASSWORD: ${PRO_ADMIN_PASSWORD}
    DOCKER_GWBRIDGE_IP: ${PRO_DOCKER_GWBRIDGE_IP}
    UI_AUTH: ${PRO_UI_AUTH}
    PUBLIC_HOSTNAME: ${PRO_PUBLIC_HOSTNAME}
  script:
    - create-nets.sh metric-net
    - >
      deploy.sh ADMIN_USER=${ADMIN_USER} ADMIN_PASSWORD=${ADMIN_PASSWORD} DOCKER_GWBRIDGE_IP=${DOCKER_GWBRIDGE_IP}
      UI_AUTH=${UI_AUTH} PUBLIC_HOSTNAME=${PUBLIC_HOSTNAME}
  environment:
    name: pro
  only:
    - master
  when: manual
