version: '3.5'

volumes:
  prometheus:
    name: prometheus-vol

  pushgateway:
    name: pushgateway-vol

  grafana:
    name: grafana-vol

  alertmanager:
    name: alertmanager-vol

  grafana-etc:
    name: grafana-etc-vol

  grafana-log:
    name: grafana-log-vol

  dockerd-exporter:
    name: dockerd-exporter-vol
