version: '3.5'

services:
  grafana:
    deploy:
      placement:
        constraints:
          - node.role == manager

  pushgateway:
    deploy:
      placement:
        constraints:
          - node.role == worker

volumes:
  grafana:
    name: ${GRAFANA_VOL_NAME:-grafana-vol}
    driver: 'cloudstor:aws'
    driver_opts:
      backing: relocatable
      size: 1
      ebstype: gp2
