version: '3.5'

services:
  grafana:
    deploy:
      placement:
        constraints:
          - node.role == manager

  pushgateway:
    deploy:
      placement:
        constraints:
          - node.role == worker

  prometheus:
    deploy:
      placement:
        constraints:
          - node.role == worker

volumes:
  prometheus:
    name: prometheus-vol
    driver: "cloudstor:aws"
    driver_opts:
      backing: relocatable
      size: 5
      ebstype: gp2

  pushgateway:
    name: pushgateway-vol

  grafana:
    name: grafana-vol
    driver: "cloudstor:aws"
    driver_opts:
      backing: relocatable
      size: 1
      ebstype: gp2

  alertmanager:
    name: alertmanager-vol

  grafana-etc:
    name: grafana-etc-vol

  grafana-log:
    name: grafana-log-vol

  dockerd-exporter:
    name: dockerd-exporter-vol
